name: new_born_nest
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  otp_text_field: ^1.1.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image1.png
    - assets/Vector.png
    - assets/littlebaby.png
    - assets/baby2.png
    - assets/lines.png
    - assets/image3.png
    - assets/lines2.png
    - assets/image4.jpg
    - assets/image5.png
    - assets/babygirl.png
    - assets/babygirl2.png
    - assets/babyboy.png
    - assets/image6.png
    - assets/image7.png
    - assets/image8.png
    - assets/image9.png
    - assets/image10.png
    - assets/image11.png
    - assets/image12.png
    - assets/image13.png
    - assets/image14.png
    - assets/image15.png
    - assets/image16.png
    - assets/image17.png
    - assets/image18.png
    - assets/image19.png
    - assets/image20.png
    - assets/image21.png
    - assets/image22.png
    - assets/image23.png
    - assets/image24.png
    - assets/image25.png
    - assets/image26.png
    - assets/image27.png
    - assets/image28.png
    - assets/images/image29.png
    - assets/images/image30.png
    - assets/images/image31.png
    - assets/images/image32.png
    - assets/images/image33.png
    - assets/images/image34.png
    - assets/images/image35.png
    - assets/images/image36.png
    - assets/images/image37.png
    - assets/images/image38.png
    - assets/images/image39.png
    - assets/images/image40.png
    - assets/images/image41.png
    - assets/images/elipse1.jpg
    - assets/images/rectangle1.jpg
    - assets/images/elipse2.png
    - assets/images/elipse3.png
    - assets/images/elipse4.png
    - assets/images/elipse5.png
    - assets/images/rectangle2.png
    - assets/images/rectangle3.png
    - assets/images/rectangle4.png
    - assets/images/rectangle5.png
    - assets/images/rectangle6.png
    - assets/images/tag.png
    - assets/images/detailphoto.png
    - assets/images/babylotion1.png
    - assets/images/babylotion2.png
    - assets/images/babylotion3.png
    - assets/images/babylotion4.png
    - assets/images/lotion.png
    - assets/images/succesful.png
    - assets/images/check.png
    - assets/images/kid.jpg
    - assets/images/success.png
    - assets/images/menu.png
    - assets/images/search.png
    - assets/images/bag.png
    - assets/images/notification.png
    - assets/images/categories.png
    - assets/images/share.png
    - assets/images/filter.png
    - assets/images/truck.png
    - assets/images/security.png
    - assets/images/done.png
    - assets/images/Successfull.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: KaushanScript
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Inter
      fonts:
        - asset: fonts/Inter-SemiBold.ttf
    - family: Inter2
      fonts:
        - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
